\c olafolio_fruits; 

INSERT INTO fruits (name, recipes, health_benefit, image, nutrition_info, description)
VALUES
 ('Banana', 'Bananas are a popular fruit that happens to provide numerous health benefits. Among other things, they may boost digestive and heart health due to their fiber and antioxidant content.', 'Bananas are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Bananas are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Banana Bread, Banana Pudding, Banana Cream Pie, Banana Split, Banana Chips, Banana Pancakes, Banana Smoothie, Banana Muffins, Banana Ice Cream, Banana Foster', 'Bananas are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
    
    ('Orange', 'Oranges are among the world’s most popular fruits. Also called sweet oranges, they grow on orange trees (Citrus x sinensis) and belong to a large group of fruits known as citrus fruits.', 'Oranges are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Oranges are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Orange Juice, Orange Marmalade, Orange Cake, Orange Salad, Orange Smoothie, Orange Sorbet, Orange Ice Cream, Orange Pie, Orange Sauce, Orange Jelly', 'Oranges are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
    
    ('Grapes', 'Grapes are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Grapes are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'Grapes are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Grapes, which can have numerous health benefits. Grapes are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Grape Juice, Grape Jelly, Grape Salad, Grape Smoothie, Grape Sorbet, Grape Ice Cream, Grape Pie, Grape Sauce, Grape Muffins, Grape Popsicles', 'Grapes are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),

        ('Strawberry', 'Strawberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Strawberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'Strawberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Strawberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Strawberry Shortcake, Strawberry Jam, Strawberry Pie, Strawberry Smoothie, Strawberry Ice Cream, Strawberry Salad, Strawberry Cake, Strawberry Muffins, Strawberry Sauce, Strawberry Sorbet', 'Strawberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Pineapple', 'Pineapple is a tropical fruit with a unique and refreshing taste. It’s rich in vitamins, minerals, and antioxidants, making it a great addition to your diet.', 'Pineapple is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Pineapple is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Pineapple Juice, Pineapple Upside-Down Cake, Pineapple Salsa, Pineapple Smoothie, Pineapple Sorbet, Pineapple Salad, Pineapple Cake, Pineapple Muffins, Pineapple Ice Cream, Pineapple Sauce', 'Pineapple is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Watermelon', 'Watermelon is a delicious and refreshing fruit that’s also good for you. It contains only 46 calories per cup but is high in vitamin C, vitamin A, and many healthy plant compounds.', 'Watermelon is a good source of fiber and vitamin sugar and water. It also contain polyphenols, which can have numerous health benefits. Watermelon is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Watermelon Juice, Watermelon Salad, Watermelon Smoothie, Watermelon Sorbet, Watermelon Cake, Watermelon Ice Cream, Watermelon Salsa, Watermelon Popsicles, Watermelon Jelly, Watermelon Soup', 'Watermelon is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Mango', 'Mango is a tropical fruit that is rich in vitamins, minerals, and antioxidants. It has been associated with many health benefits, including improved immunity, digestive health, and eyesight.', 'Mango is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Mango is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Mango Juice, Mango Salsa, Mango Smoothie, Mango Sorbet, Mango Salad, Mango Cake, Mango Ice Cream, Mango Popsicles, Mango Jelly, Mango Soup', 'Mango is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Kiwi', 'Kiwi is a small fruit with a lot of flavor and plenty of health benefits. It’s also full of nutrients like vitamin C, K, and E.', 'Kiwi is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Kiwi is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Kiwi Juice Kiwi Salad, Kiwi Smoothie, Kiwi Sorbet, Kiwi Cake, Kiwi Ice Cream, Kiwi Popsicles, Kiwi Jelly, Kiwi Soup', 'Kiwi is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Peach', 'Peaches are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health.', 'Peaches are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Peaches are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Peach Juice, Peach Cobbler, Peach Pie, Peach Smoothie, Peach Sorbet, Peach Salad, Peach Cake, Peach Ice Cream, Peach Popsicles, Peach Jelly', 'Peaches are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Cherry', 'Cherries are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health.', 'Cherries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Cherries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Cherry Juice, Cherry Cobbler, Cherry Pie, Cherry Smoothie, Cherry Sorbet, Cherry Salad, Cherry Cake, Cherry Ice Cream, Cherry Popsicles, Cherry Jelly', 'Cherries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Blueberry', 'Blueberries are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Blueberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Blueberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Blueberry Juice, Blueberry Cobbler, Blueberry Pie, Blueberry Smoothie, Blueberry Sorbet, Blueberry Salad, Blueberry Cake, Blueberry Ice Cream, Blueberry Popsicles, Blueberry Jelly', 'Blueberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Raspberry', 'Raspberries are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Raspberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Raspberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Raspberry Juice, Raspberry Cobbler, Raspberry Pie, Raspberry Smoothie, Raspberry Sorbet, Raspberry Salad, Raspberry Cake, Raspberry Ice Cream, Raspberry Popsicles, Raspberry Jelly', 'Raspberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Blackberry', 'Blackberries are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Blackberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Blackberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Blackberry Juice, Blackberry Cobbler, Blackberry Pie, Blackberry Smoothie, Blackberry Sorbet, Blackberry Salad, Blackberry Cake, Blackberry Ice Cream, Blackberry Popsicles, Blackberry Jelly', 'Blackberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Cranberry', 'Cranberries are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Cranberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Cranberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Cranberry Juice, Cranberry Cobbler, Cranberry Pie, Cranberry Smoothie, Cranberry Sorbet, Cranberry Salad, Cranberry Cake, Cranberry Ice Cream, Cranberry Popsicles, Cranberry Jelly', 'Cranberries are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Pomegranate', 'Pomegranates are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Pomegranates are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Pomegranates are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Pomegranate Juice, Pomegranate Cobbler, Pomegranate Pie, Pomegranate Smoothie, Pomegranate Sorbet, Pomegranate Salad, Pomegranate Cake, Pomegranate Ice Cream, Pomegranate Popsicles, Pomegranate Jelly', 'Pomegranates are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Mandarin', 'Mandarins are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Mandarins are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Mandarins are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Mandarin Juice, Mandarin Cobbler, Mandarin Pie, Mandarin Smoothie, Mandarin Sorbet, Mandarin Salad, Mandarin Cake, Mandarin Ice Cream, Mandarin Popsicles, Mandarin Jelly', 'Mandarins are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Lemon', 'Lemons are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Lemons are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Lemons are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Lemon Juice, Lemon Cobbler, Lemon Pie, Lemon Smoothie, Lemon Sorbet, Lemon Salad, Lemon Cake, Lemon Ice Cream, Lemon Popsicles, Lemon Jelly', 'Lemons are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Lime', 'Limes are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Limes are a delicious fruit that are packed with shoulder vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Lime Juice, Lime Cobbler, Lime Pie, Lime Smoothie, Lime Sorbet, Lime Salad, Lime Cake, Lime Ice Cream, Lime Popsicles, Lime Jelly', 'Limes are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.'),
        
        ('Grapefruit', 'Grapefruits are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Grapefruits are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Grapefruits are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Grapefruit Juice, Grapefruit Cobbler, Grapefruit Pie, Grapefruit Smoothie, Grapefruit Sorbet, Grapefruit Salad, Grapefruit Cake, Grapefruit Ice Cream, Grapefruit Popsicles, Grapefruit Jelly', 'Grapefruits are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Coconut', 'Coconuts are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Coconuts are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Coconuts are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Coconut produced by the coconut palm, a member of the family Arecaceae. The term coconut can refer to the whole coconut palm, the seed, or the fruit, which botanically is a drupe, not a nut. The term is derived from the 16th-century Portuguese and Spanish word coco, meaning head or skull, after the three indentations on the coconut shell that resemble facial features.', 'Coconuts are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Avocado', 'Avocados are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Avocados are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Avocados are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Avocado Juice, Avocado Cobbler, Avocado Pie, Avocado Smoothie, Avocado Sorbet, Avocado Salad, Avocado Cake, Avocado Ice Cream, Avocado Popsicles, Avocado Jelly', 'Avocados are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Papaya', 'Papayas are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Papayas are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Papayas are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Papaya Juice, Papaya Cobbler, Papaya Pie, Papaya Smoothie, Papaya Sorbet, Papaya Salad, Papaya Cake, Papaya Ice Cream, Papaya Popsicles, Papaya Jelly', 'Papayas are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Pears', 'Pears are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Pears are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Pears are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Pears Juice, Pears Cobbler, Pears Pie, Pears Smoothie, Pears Sorbet, Pears Salad, Pears Cake, Pears Ice Cream, Pears Popsicles, Pears Jelly', 'Pears are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Plums', 'Plums are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Plums are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Plums are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Plums Juice, Plums Cobbler, Plums Pie, Plums Smoothie, Plums Sorbet, Plums Salad, Plums Cake, Plums Ice Cream, Plums Popsicles, Plums Jelly', 'Plums are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Apricots', 'Apricots are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health benefits.', 'Apricots are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Apricots are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Apricots Juice, Apricots Cobbler, Apricots Pie, Apricots Smoothie, Apricots Sorbet, Apricots Salad, Apricots Cake, Apricots Ice Cream, Apricots Popsicles, Apricots Jelly', 'Apricots are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Nectarines', 'Nectarines are a delicious fruit that are packed with vitamins, minerals, and antioxidants. They have many health benefits, including improved digestion and heart health benefits and improved health.', 'Nectarines are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Nectarines are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Nectarines Juice, Nectarines Cobbler, Nectarines Pie, Nectarines Smoothie, Nectarines Sorbet, Nectarines Salad, Nectarines Cake, Nectarines Ice Cream, Nectarines Popsicles, Nectarines Jelly', 'Nectarines are a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Guava', 'Guava is a tropical fruit that is rich in vitamins, minerals, and antioxidants. It has been associated with many health benefits, including improved immunity, digestive health, and eyesight.', 'Guava is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Guava is a good source of fiber and vitamin C. They also contain polyphenols, which can have several health benefits. Guava is a good source of fiber and neighbouring C. They also contain polyphenols and can have several health benefits. Guava is a good source of fiber and neighbouring C. They also contain polyphenols and can have several health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Guava Juice, Guava Cobbler, Guava Pie, Guava Smoothie, Guava Sorbet, Guava Salad, Guava Cake, Guava Ice Cream, Guava Popsicles, Guava Jelly', 'Guava is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Dragon Fruit', 'Dragon fruit is a tropical fruit that is rich in vitamins, minerals, and antioxidants. It has been associated with many health benefits, including improved immunity, digestive health, and eyesight.', 'Dragon fruit is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Dragon fruit is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Dragon Fruit Juice, Dragon Fruit Cobbler, Dragon Fruit Pie, Dragon Fruit Smoothie, Dragon Fruit Sorbet, Dragon Fruit Salad, Dragon Fruit Cake, Dragon Fruit Ice Cream, Dragon Fruit Popsicles, Dragon Fruit Jelly', 'Dragon fruit is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Passion Fruit', 'Passion fruit is a tropical fruit that is rich in vitamins, minerals, and antioxidants. It has been associated with many health benefits, including improved immunity, digestive health, and eyesight.', 'Passion fruit is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Passion fruit is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Passion Fruit Juice, Passion Fruit Cobbler, Passion Fruit Pie Passion Fruit Smoothie, Passion Fruit Sorbet, Passion Fruit Salad, Passion Fruit Cake, Passion Fruit Ice Cream, Passion Fruit Popsicles, Passion Fruit Jelly', 'Passion fruit is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.'),
        
        ('Lychee', 'Lychee is a tropical fruit that is rich in vitamins, minerals, and antioxidants. It has been associated with many health benefits, including improved immunity, digestive health, and eyesight.', 'Lychee is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits. Lychee is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.', 'https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Lychee Juice, Lychee Cobbler, Lychee Pie, Lychee Smoothie, Lychee Sorbet, Lychee Salad, Lychee Cake, Lychee Ice Cream, Lychee Popsicles, Lychee Jelly', 'Lychee is a good source of fiber and vitamin C. They also contain polyphenols, which can have numerous health benefits.');

