INSERT INTO fruits (name, recipes, health_benefit, image, nutrition_info, description)
VALUES
  ('Pear', 'Pear Salad, Pear Tart', 'Pears are high in fiber and may promote gut health.', 'https://example.com/pear.jpg', 'Pears are a good source of vitamin C, potassium, and antioxidants.', 'Pears are sweet, bell-shaped fruits...'),
  ('Plum', 'Plum Jam, Plum Pie', 'Plums are rich in vitamins and minerals and may have benefits for heart health.', 'https://example.com/plum.jpg', 'Plums are low in calories and contain vitamins A, C, and K.', 'Plums are small, round fruits...'),
  ('Apricot', 'Apricot Jam, Apricot Smoothie', 'Apricots are rich in vitamins A and C and may promote eye health.', 'https://example.com/apricot.jpg', 'Apricots are a good source of fiber and antioxidants.', 'Apricots are small, orange fruits...'),
  ('Papaya', 'Papaya Salad, Papaya Smoothie', 'Papayas are rich in vitamins A and C and may aid digestion.', 'https://example.com/papaya.jpg', 'Papayas contain an enzyme called papain, which may help with digestion.', 'Papayas are tropical fruits...'),
  ('Grapefruit', 'Grapefruit Salad, Grapefruit Smoothie', 'Grapefruits are high in vitamins A and C and may help with weight loss.', 'https://example.com/grapefruit.jpg', 'Grapefruits are low in calories and high in fiber.', 'Grapefruits are large, round fruits...'),
  ('Cantaloupe', 'Cantaloupe Salad, Cantaloupe Smoothie', 'Cantaloupes are hydrating and may promote skin health.', 'https://example.com/cantaloupe.jpg', 'Cantaloupes are low in calories and contain vitamins A and C.', 'Cantaloupes are large, oval fruits...'),
  ('Honeydew', 'Honeydew Salad, Honeydew Smoothie', 'Honeydews are hydrating and may support heart health.', 'https://example.com/honeydew.jpg', 'Honeydews are low in calories and contain vitamins C and K.', 'Honeydews are round, juicy fruits...'),
  ('Blackberry', 'Blackberry Jam, Blackberry Smoothie', 'Blackberries are high in antioxidants and may support brain health.', 'https://example.com/blackberry.jpg', 'Blackberries are low in calories and contain vitamins C and K.', 'Blackberries are small, black or dark purple...'),
  ('Cranberry', 'Cranberry Sauce, Cranberry Smoothie', 'Cranberries are rich in antioxidants and may help prevent urinary tract infections.', 'https://example.com/cranberry.jpg', 'Cranberries are low in calories and high in vitamin C and fiber.', 'Cranberries are small, red fruits...'),
  ('Coconut', 'Coconut Curry, Coconut Smoothie', 'Coconuts are rich in healthy fats and may support heart health.', 'https://example.com/coconut.jpg', 'Coconuts contain vitamins, minerals, and antioxidants.', 'Coconuts are tropical fruits with a hard, brown shell...'),
  ('Lychee', 'Lychee Sorbet, Lychee Smoothie', 'Lychees are rich in vitamin C and may support immune health.', 'https://example.com/lychee.jpg', 'Lychees are low in calories and contain vitamins B and C.', 'Lychees are small, round fruits with a bumpy red shell...'),
  ('Mangosteen', 'Mangosteen Salad, Mangosteen Smoothie', 'Mangosteens are rich in antioxidants and may have anti-inflammatory effects.', 'https://example.com/mangosteen.jpg', 'Mangosteens are low in calories and contain vitamins and minerals.', 'Mangosteens are tropical fruits with a purple rind...'),
  ('Passion Fruit', 'Passion Fruit Jam, Passion Fruit Smoothie', 'Passion fruits are high in fiber and may support digestive health.', 'https://example.com/passionfruit.jpg', 'Passion fruits are low in calories and contain vitamins and antioxidants.', 'Passion fruits are small, round fruits with a tough outer shell...'),
  ('Pomegranate', 'Pomegranate Salad, Pomegranate Smoothie', 'Pomegranates are high in antioxidants and may support heart health.', 'https://example.com/pomegranate.jpg', 'Pomegranates contain vitamins C and K, folate, and potassium.', 'Pomegranates are round fruits with a tough outer skin...'),
  ('Dragon Fruit', 'Dragon Fruit Salad, Dragon Fruit Smoothie', 'Dragon fruits are rich in vitamins and minerals and may support skin health.', 'https://example.com/dragonfruit.jpg', 'Dragon fruits are low in calories and contain vitamin C, fiber, and antioxidants.', 'Dragon fruits are tropical fruits with a vibrant pink or yellow skin...'),
  ('Guava', 'Guava Jam, Guava Smoothie', 'Guavas are rich in vitamin C and may support immune health.', 'https://example.com/guava.jpg', 'Guavas are low in calories and contain fiber, vitamins, and minerals.', 'Guavas are tropical fruits with a green or yellow skin...'),
  ('Kiwi Berry', 'Kiwi Berry Salad, Kiwi Berry Smoothie', 'Kiwi berries are rich in vitamin C and may support immune health.', 'https://example.com/kiwiberry.jpg', 'Kiwi berries are low in calories and contain fiber and antioxidants.', 'Kiwi berries are small fruits similar in appearance to kiwis...'),
  ('Mamey Sapote', 'Mamey Sapote Sorbet, Mamey Sapote Smoothie', 'Mamey sapotes are rich in vitamins and minerals and may support heart health.', 'https://example.com/mameysapote.jpg', 'Mamey sapotes are low in calories and contain fiber, vitamins, and antioxidants.', 'Mamey sapotes are tropical fruits with a brown, rough skin...'),
  ('Star Fruit', 'Star Fruit Salad, Star Fruit Smoothie', 'Star fruits are low in calories and may support digestive health.', 'https://example.com/starfruit.jpg', 'Star fruits are rich in vitamin C and antioxidants.', 'Star fruits are tropical fruits with a star-shaped cross-section...'),
  ('Tamarillo', 'Tamarillo Jam, Tamarillo Smoothie', 'Tamarillos are rich in vitamins and minerals and may support eye health.', 'https://example.com/tamarillo.jpg', 'Tamarillos are low in calories and contain fiber and antioxidants.', 'Tamarillos are oval-shaped fruits...');

